### ISSUE TITLE
Fill in all service doc pages

### ISSUE THREAD

**Issue by ivalaginja** [spacetelescope/catkit2#190]
Unchecked services that already have some content need to be double-checked and sometimes updated with driver information.

- [x] AimTTi PL-P - @ivalaginja - https://github.com/spacetelescope/catkit2/pull/196
- [x] AlliedVision camera - @ivalaginja - https://github.com/spacetelescope/catkit2/pull/185
- [x] BMC DM - @steigersg - https://github.com/spacetelescope/catkit2/pull/224
- [x] Camera sim - @steigersg  #252 
- [x] Empty service - @ivalaginja - https://github.com/spacetelescope/catkit2/pull/196
- [x] FLIR camera - @steigersg - https://github.com/spacetelescope/catkit2/pull/224
- [x] Newport Picomotor - @meiji274 - https://github.com/spacetelescope/catkit2/pull/197
- [x] Newport XPS - @ivalaginja - #279 
- [x] NI DAQ - @ivalaginja - https://github.com/spacetelescope/catkit2/pull/196
- [x] NKT Super K - @steigersg - https://github.com/spacetelescope/catkit2/pull/224
- [x] Omega ITHX - already existed
- [x] Safety Manual Check - @ivalaginja - #279 
- [x] Safety Monitor - already there
- [x] SNMP UPS - already there
- [x] Thorlabs CLD 101x - @ivalaginja - https://github.com/spacetelescope/catkit2/pull/196
- [x] Thorlabs filter wheel - @steigersg #252 
- [x] Thorlabs flip mount - @steigersg  #252 
- [x] Thorlabs ~picomotor~ pm -> need to rename to "power meter" - @ivalaginja - #279 
- [x] Thorlabs TSP temperature sensor - @steigersg  #252
- [x] Web Power Switch - @meiji274 - https://github.com/spacetelescope/catkit2/pull/197
- [x] ZWO camera - @meiji274 - https://github.com/spacetelescope/catkit2/pull/197

General guidelines:
- use provided template
- general description should list required drivers, Python APIs, and models a service has been tested on
- service properties can be identified with `make_property()`
- service commands can be identified with `make_command()`
- data streams can be identified with `make_data_stream()`

**Comment by steigersg** [comment]
Do we need to revise the bmc_dm documentation now that we have the new DM base class?

**Comment by ivalaginja** [comment]
At some point probably, but I have added the note `(Old)` to that documentation and filled in the new doc page for the new services. So I think it's fine for now, but don't let me stop you if you want to update things.
